# This workflow will run build an AS project and save the libraries to a pipeline artifact
trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*

jobs:
- job: build_publish_libraries
  pool:
    name: 'AutomationStudioPool'
  steps:
  - checkout: self
    clean: true
    fetchDepth: 0
    fetchTags: true
    lfs: true
    persistCredentials: true
    submodules: recursive
    path: "main"
    displayName: 'Checkout repository'

  - script: python.exe C:/Tools/AsPython/InstallUpgrades.py $(Build.SourcesDirectory)/upgrades -asp AS411 -r --logLevel DEBUG
    displayName: 'Install AS upgrades'

  - script: python.exe C:/Tools/AsPython/CmdLineBuild.py $(Build.SourcesDirectory)/example/AsProject/AsProject.apj -c Intel ARM -bm Rebuild -sim --logLevel DEBUG
    displayName: 'Build project'

  - script: python.exe C:/Tools/AsPython/CmdLineExportLib.py $(Build.SourcesDirectory)/example/AsProject/AsProject.apj -dest ./libs -c Intel ARM -wl vartools -l DEBUG -o -bm "None"
    displayName: 'Export libraries'

  - task: UniversalPackages@0
    inputs:
      command: 'publish'
      publishDirectory: '$(Pipeline.Workspace)/main/libs/vartools'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: '1fa8a184-d390-4c05-8b59-19ab4ca4ef5f/ca506b3f-058b-4008-bf84-27c4d22b5b4c'
      vstsFeedPackagePublish: 'vartools'
      versionOption: 'patch'
