# This workflow will run build an AS project and publish the libraries to the github package registry

name: Build Libraries

on:
  push:
    branches: feature/runner

jobs:
  get-runner:
    runs-on: self-hosted
    if: ${{ always() }}
    outputs:
     RUNNER: ${{ runner.name }}

  depends:
    needs: get-runner
    runs-on: ${{needs.get-runner.outputs.RUNNER}}
    strategy:
      matrix:
        dependency: ${{fromJson('[{"repo":"loupeteam/AsGithubAction","ref":"main","path":"AsGithubAction"},{"repo":"loupeteam/ASPython", "ref":"feature/libraryRefs","path":"AsPython"}, {"repo":"loupeteam/LPM", "ref":"develop", "path":"LPM"}]')}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.dependency.repo }}
          ref: ${{ matrix.dependency.ref }}
          path: ${{ matrix.dependency.path }}
          token: ${{ secrets.GA_PAT }} # `GH_PAT` is a secret that contains your PAT
      
  clone:
    needs: get-runner
    runs-on: ${{needs.get-runner.outputs.RUNNER}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main          

  build:
    needs: [get-runner,clone,depends]
    runs-on: ${{needs.get-runner.outputs.RUNNER}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: python.exe ./AsPython/CmdLineBuild.py ./main/example/AsProject/AsProject.apj -c Intel ARM -bm Rebuild --logLevel DEBUG

  export:
    needs: [get-runner,build]
    runs-on: ${{needs.get-runner.outputs.RUNNER}}
    permissions:
      contents: read
      packages: write
    steps:
      - run: python.exe ./AsPython/CmdLineExportLib.py ./main/example/AsProject/AsProject.apj -dest ./libs -c Intel ARM -wl vartools -l DEBUG -o -bm "None"

  login:
    needs: [depends, get-runner]
    runs-on: ${{needs.get-runner.outputs.RUNNER}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./AsGithubAction
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [login, export, get-runner]
    runs-on: ${{needs.get-runner.outputs.RUNNER}}
    strategy:
      matrix:
        packages: [vartools]
    permissions:
      contents: read
      packages: write
    steps:
      - run: | 
          cd ./libs/${{ matrix.packages }}
          lpm init -s -lib -nc
          lpm publish -s -nc



