# This workflow will run build an AS project and publish the libraries to the github package registry

name: Build Libraries

on:
  push:
    branches: feature/runner

jobs:
  depends:
    runs-on: self-hosted
    strategy:
      matrix:
        dependency: ${{fromJson('[{"repo":"loupeteam/AsGithubAction","ref":"main","path":"AsGithubAction"},{"repo":"loupeteam/ASPython", "ref":"feature/libraryRefs","path":"AsPython"}, {"repo":"loupeteam/LPM", "ref":"develop", "path":"LPM"}]')}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.dependency.repo }}
          ref: ${{ matrix.dependency.ref }}
          path: ${{ matrix.dependency.path }}
          token: ${{ secrets.GA_PAT }} # `GH_PAT` is a secret that contains your PAT

  dependsV2:
    runs-on: self-hosted
    strategy:
      matrix:
        dependency: [main, AsGithubAction, ASPython, LPM]
        includes:
        - dependency: main
          path: main
        - dependency: AsGithubAction
          repo: loupeteam/AsGithubAction
          ref: main
          path: AsGithubAction
        - dependency: ASPython
          repo: loupeteam/ASPython
          ref: feature/libraryRefs
          path: AsPython
        - dependency: LPM
          repo: loupeteam/LPM
          ref: develop
          path: LPM
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GA_PAT }} # `GH_PAT` is a secret that contains your PAT
        - if: ${{ matrix.path }}
          path: ${{ matrix.path }}
        - if: ${{ matrix.repo }}          
          repository: ${{ matrix.repo }}
        - if: ${{ matrix.ref }}
          ref: ${{ matrix.ref }}
                  
  clone:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main          

  build:
    needs: [clone,depends]
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: python.exe ./AsPython/CmdLineBuild.py ./main/example/AsProject/AsProject.apj -c Intel ARM -bm Rebuild --logLevel DEBUG

  export:
    needs: [build]
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - run: python.exe ./AsPython/CmdLineExportLib.py ./main/example/AsProject/AsProject.apj -dest ./libs -c Intel ARM -wl vartools -l DEBUG -o -bm "None"

  login:
    needs: [depends]
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./AsGithubAction
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [login, export]
    runs-on: self-hosted
    strategy:
      matrix:
        packages: [vartools]
    permissions:
      contents: read
      packages: write
    steps:
      - run: | 
          cd ./libs/${{ matrix.packages }}
          lpm init -s -lib -nc
          lpm publish -s -nc



