# This workflow will run build an AS project and publish the libraries to the github package registry

name: Build Publish Libraries

on:
  push:
    branches:
      - main
    tags:
      - v*
      

jobs:
  build-publish-libraries:
    runs-on: [AS411, ephemeral]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          path: "main"
          lfs: true
      - uses: actions/checkout@v4
        with:
          repository: "loupeteam/ASPython"
          submodules: 'true'
          ref: "bugfix/pvi-error-code"
          path: "AsPython"
      - uses: actions/checkout@v4
        with:
          repository: "loupeteam/LPM"
          submodules: 'true'
          ref: "main"
          path: "LPM"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Fix LFS
        run:  |
          cd ./main
          git lfs pull
      - name: Install AS upgrades
        shell: pwsh
        run: |
          Set-Location -Path ./main/upgrades
          & $PWD/install.ps1
      - run: python.exe ./AsPython/CmdLineBuild.py ./main/example/AsProject/AsProject.apj -c Intel ARM -bm Rebuild -sim --logLevel DEBUG
      - run: python.exe ./AsPython/CmdLineExportLib.py ./main/example/AsProject/AsProject.apj -dest ./libs -c Intel ARM -wl vartools -l DEBUG -o -bm "None"
      - uses: ./AsGithubAction
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: | 
          cd ./libs/vartools
          python.exe ${{ github.workspace }}/LPM/src/LPM.py login -s -t ${{ secrets.GITHUB_TOKEN }} -nc
          python.exe ${{ github.workspace }}/LPM/src/LPM.py init -s -lib -nc
          python.exe ${{ github.workspace }}/LPM/src/LPM.py publish -s -nc