# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: feature/runner

jobs:
  depends:
    runs-on: self-hosted
    strategy:
      matrix:
        dependency: ${{fromJson('[{"repo":"loupeteam/AsGithubAction","ref":"main","path":"AsGithubAction"},{"repo":"loupeteam/ASPython", "ref":"feature/libraryRefs","path:AsPython"}, {"repo":"loupeteam/LPM", "ref:develop", "path:LPM"}]')}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.dependency.repo }}
          ref: ${{ matrix.dependency.ref }}
          path: ${{ matrix.dependency.path }}
          token: ${{ secrets.GA_PAT }} # `GH_PAT` is a secret that contains your PAT

  build:
    runs-on: self-hosted
    needs: depends
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main          
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: ./AsGithubAction
        with:
          milliseconds: 2000
      - run: python.exe ./AsPython/CmdLineBuild.py ./main/example/AsProject/AsProject.apj -c Intel ARM -bm Rebuild --logLevel DEBUG
      - run: python.exe ./AsPython/CmdLineExportLib.py ./main/example/AsProject/AsProject.apj -dest ./libs -c Intel ARM -wl vartools -l DEBUG -o -bm "None"

  publish:
    needs: build
    runs-on: self-hosted
    strategy:
      matrix:
        packages: [libs/vartools]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com"
          package: ${{ matrix.packages }}
      - run: | 
          cd ./${{ matrix.packages }}
          lpm init -s -lib -nc
          lpm publish -s -nc



