# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: feature/runner

jobs:
  depends:
    runs-on: self-hosted
    strategy:
      max-parallel: 5
      matrix:
        dependency: ${{fromJson('[{"repo":"loupeteam/AsGithubAction","ref":"main","path":"AsGithubAction"},{"repo":"loupeteam/ASPython", "ref":"feature/libraryRefs","path":"AsPython"}, {"repo":"loupeteam/LPM", "ref":"develop", "path":"LPM"}]')}}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.dependency.repo }}
          ref: ${{ matrix.dependency.ref }}
          path: ${{ matrix.dependency.path }}
          token: ${{ secrets.GA_PAT }} # `GH_PAT` is a secret that contains your PAT

  clone:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main          

  build:
    runs-on: self-hosted
    needs: [clone,depends]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: python.exe ./AsPython/CmdLineBuild.py ./main/example/AsProject/AsProject.apj -c Intel ARM -bm Rebuild --logLevel DEBUG

  export:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - run: python.exe ./AsPython/CmdLineExportLib.py ./main/example/AsProject/AsProject.apj -dest ./libs -c Intel ARM -wl vartools -l DEBUG -o -bm "None"

  login:
    runs-on: self-hosted
    needs: [depends]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: ./AsGithubAction
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [login, export]
    runs-on: self-hosted
    strategy:
      matrix:
        packages: [vartools]
    permissions:
      contents: read
      packages: write
    steps:
      - run: | 
          cd ./libs/${{ matrix.packages }}
          lpm init -s -lib -nc
          lpm publish -s -nc



