# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: feature/runner

jobs:
  publish-main:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main          
      - uses: actions/checkout@v4
        with:
          repository: loupeteam/AsGithubAction
          ref: main
          path: tools/AsGithubAction          
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/