# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: feature/runner

jobs:
  publish-main:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: main          
      - uses: actions/checkout@v4
        with:
          repository: loupeteam/AsGithubAction
          ref: main
          path: AsGithubAction          
          token: ${{ secrets.GA_PAT }} # `GH_PAT` is a secret that contains your PAT
      - uses: actions/checkout@v4
        with:
          repository: loupeteam/ASPython
          ref: feature/libraryRefs
          path: AsPython          
          token: ${{ secrets.GA_PAT }} # `GH_PAT` is a secret that contains your PAT
      - uses: actions/checkout@v4
        with:
          repository: loupeteam/LPM
          ref: develop
          path: LPM          
          token: ${{ secrets.GA_PAT }} # `GH_PAT` is a secret that contains your PAT
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: ./AsGithubAction
        with:
          milliseconds: 2000
      - run: python.exe ./AsPython/CmdLineBuild.py ./main/example/AsProject/AsProject.apj -c Intel ARM -bm Rebuild --logLevel DEBUG
      - run: python.exe ./AsPython/CmdLineExportLib.py ./main/example/AsProject/AsProject.apj -dest ./libs -c Intel ARM -wl vartools -l DEBUG -o -bm "None"
      - run: | 
          cd ./libs/vartools
          python.exe ../../LPM/src/lpm.py init -s -lib -nc
          python.exe ../../LPM/src/lpm.py publish -s -nc
